# 임시  코드 
version: '3.8'

services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_NAME=yahoo_comments
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - yahoo-network
    volumes:
      - ./logs:/app/logs
     #- ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: on-failure

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=yahoo_comments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - yahoo-network

networks:
  yahoo-network:
    driver: bridge

volumes:
  db-data: